import { useState } from 'react'
import { counselingTopics, guardianRelations, safetyQuestions, type CounselingTopic, type GuardianRelation, type RequestDetails, type Screening } from './counseling'
import { type SchoolType } from './roster'
import { ShieldCheck } from 'lucide-react'
export default function CounselingForm({ name, grade, schoolClass, schoolType, error, onSubmit }: { name: string; grade: string; schoolClass: string; schoolType: SchoolType; error: string; onSubmit: (details: RequestDetails) => void }) {
  const [phoneDigits, setPhoneDigits] = useState('')
  const contact = `010-${phoneDigits.slice(0, 4)}-${phoneDigits.slice(4)}`
  const [noContact, setNoContact] = useState(false)
  const [guardianRelation, setGuardianRelation] = useState<GuardianRelation | ''>('')
  const [topics, setTopics] = useState<CounselingTopic[]>([])
  const canSkipContact = schoolType === 'elementary' && (grade === '1학년' || grade === '2학년')
  const contactUnknown = canSkipContact && noContact
  const [answers, setAnswers] = useState<Partial<Screening>>({})
  const [validation, setValidation] = useState('')
  const urgent = answers.immediate === 'yes'
  const needsAdult = Object.values(answers).some(value => value === 'yes')
  return <form className="counseling-form" onSubmit={event => { event.preventDefault(); if (!contactUnknown && !guardianRelation) { setValidation('보호자와의 관계를 골라 주세요.'); return } if (!contactUnknown && phoneDigits.length !== 8) { setValidation('010 뒤의 전화번호 숫자 8자리를 적어 주세요.'); return } if (!topics.length) { setValidation('이야기하고 싶은 고민을 하나 이상 골라 주세요.'); return } if (Object.keys(answers).length !== 3) { setValidation('아직 답하지 않은 질문이 있어요. 말하기 어려우면 ‘선생님께 직접 이야기할래요’를 골라도 괜찮아요.'); return } setValidation(''); onSubmit({ contact: contactUnknown ? '' : contact, contactOwner: 'guardian', guardianRelation: contactUnknown ? undefined : guardianRelation as GuardianRelation, noContact: contactUnknown, topics, screening: answers as Screening }) }}>
    <p className="eyebrow">{grade} {schoolClass} · {name}</p><h2>상담 신청하기</h2>
    <p className="operation-help">이야기하고 싶은 고민을 고르고 보호자 전화번호를 적어 주세요.</p>
    <fieldset className="request-basics"><legend>상담 신청 내용</legend><div className="request-basics-grid"><section className="topic-section" aria-labelledby="topic-title"><h3 id="topic-title">어떤 고민인가요?</h3><p className="operation-help">여러 개 골라도 괜찮아요.</p><div className="topic-options">{(Object.entries(counselingTopics) as [CounselingTopic, string][]).map(([value, label]) => <button type="button" key={value} className={topics.includes(value) ? 'selected' : ''} aria-pressed={topics.includes(value)} onClick={() => { setTopics(topics.includes(value) ? topics.filter(topic => topic !== value) : [...topics, value]); setValidation('') }}>{label}</button>)}</div></section><section className="contact-section" aria-labelledby="contact-title"><h3 id="contact-title">보호자 전화번호</h3><p className="operation-help">부모님이나 나를 돌봐 주는 어른의 번호예요.</p><div className="guardian-contact-field"><select aria-label="보호자와의 관계" value={guardianRelation} required={!contactUnknown} disabled={contactUnknown} onChange={event => { setGuardianRelation(event.target.value as GuardianRelation | ''); setValidation('') }}><option value="">관계 선택</option>{(Object.entries(guardianRelations) as [GuardianRelation, string][]).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><div className={`guardian-phone-input ${contactUnknown ? 'disabled' : ''}`}><span aria-hidden="true">010 −</span><input aria-label="보호자 전화번호 010 뒤 8자리" type="text" autoComplete="off" inputMode="numeric" value={phoneDigits.length > 4 ? `${phoneDigits.slice(0, 4)}-${phoneDigits.slice(4)}` : phoneDigits} required={!contactUnknown} disabled={contactUnknown} placeholder="0000-0000" onChange={event => { const digits = event.target.value.replace(/\D/g, ''); setPhoneDigits((digits.length === 11 && digits.startsWith('010') ? digits.slice(3) : digits).slice(0, 8)); setValidation('') }} onPaste={event => { event.preventDefault(); const digits = event.clipboardData.getData('text').replace(/\D/g, ''); setPhoneDigits((digits.length === 11 && digits.startsWith('010') ? digits.slice(3) : digits).slice(0, 8)); setValidation('') }} /></div></div><div className="contact-bottom-row"><div className="contact-use-note"><ShieldCheck size={19} aria-hidden="true" /><span>상담 시간을 알려 줄 때 사용해요.</span></div>{canSkipContact && <button type="button" className={`admin-nav ${contactUnknown ? 'filter-selected' : ''}`} aria-pressed={contactUnknown} onClick={() => { setNoContact(!noContact); setValidation('') }}>잘 모르겠어요</button>}</div>{contactUnknown && <p className="operation-help" role="status">괜찮아요. 선생님이 보호자의 전화번호를 함께 알아봐 주실 거예요.</p>}</section></div></fieldset>
    <fieldset><legend>지금 마음은 어떤가요?</legend><p className="operation-help">내 마음에 가까운 답을 골라 주세요. 말하기 어려우면 ‘선생님께 직접 이야기할래요’를 골라도 괜찮아요.</p>{(Object.entries(safetyQuestions) as [keyof Screening, string][]).map(([key, question]) => <fieldset className="safety-question" key={key}><legend>{question}</legend><div className="safety-options">{(['yes', 'no', 'talk'] as const).map(value => <label className={answers[key] === value ? 'selected' : ''} key={value}><input type="radio" name={key} value={value} checked={answers[key] === value} onChange={() => setAnswers({ ...answers, [key]: value })} />{value === 'yes' ? '네' : value === 'no' ? '아니요' : '선생님께 직접 이야기할래요'}</label>)}</div></fieldset>)}</fieldset>
    {needsAdult && <div className="safety-help" role="status"><strong>{urgent ? '가까운 선생님이나 믿을 수 있는 어른에게 지금 바로 알려 주세요.' : '혼자 걱정하지 않아도 괜찮아요. 가까운 선생님에게 지금 이야기해 주세요.'}</strong><p>선생님이 신청을 읽기까지 시간이 걸릴 수 있어요. 지금 위험하거나 다쳤다면 기다리지 말고 가까운 선생님이나 어른에게 바로 도움을 청해 주세요.</p></div>}
    <p className="operation-help">전화번호와 답변은 상담 선생님이 읽어요. 도움이 필요할 때는 선생님이 보호자와 함께 도울 수 있어요.</p>
    {(validation || error) && <p className="record-error" role="alert">{validation || error}</p>}<button className="primary-button" type="submit">상담 신청하기</button>
  </form>
}
