import { useState } from 'react'
import { dateKey, timeLabel } from './attendance'
import { counselingTopics, guardianRelations, readRequests, requestPriority, priorityLabels, safetyQuestions, type CounselingRequest } from './counseling'
export default function CounselingInbox({ requests, onSave }: { requests: CounselingRequest[]; onSave: (requests: CounselingRequest[]) => boolean }) {
  const [filter, setFilter] = useState('pending')
  const [error, setError] = useState('')
  const rank = { urgent: 0, followup: 1, unknown: 2, regular: 3 }
  const rows = requests.filter(item => filter === 'all' || (!item.completed && (filter === 'pending' || ['urgent', 'followup'].includes(requestPriority(item.details))))).sort((a, b) => Number(a.completed) - Number(b.completed) || rank[requestPriority(a.details)] - rank[requestPriority(b.details)] || Date.parse(b.timestamp) - Date.parse(a.timestamp))
  return <><div className="safety-admin-note"><strong>답변을 읽고 학생을 직접 만나 확인해 주세요.</strong><p>이 질문만으로 학생의 위험 여부를 판단할 수 없습니다. 모두 아니요로 답했어도 학생의 상황을 직접 확인해 주세요. 바로 도움이 필요한 학생은 먼저 만나 안전을 확인하고 학교 위기 대응 절차에 따라 도와주세요.</p></div><div className="roster-actions" role="group" aria-label="상담 신청 필터">{[['pending', '확인 대기'], ['priority', '먼저 확인할 신청'], ['all', '전체']].map(([value, label]) => <button className={`admin-nav ${filter === value ? 'filter-selected' : ''}`} aria-pressed={filter === value} key={value} onClick={() => setFilter(value)}>{label}</button>)}</div>{error && <p className="record-error" role="alert">{error}</p>}
    <div className="counseling-inbox">{rows.map(item => <article key={item.id} className="request-card"><div className="panel-heading"><h3>{item.name} <small>{item.grade} {item.schoolClass}</small></h3><span className={`priority-badge ${requestPriority(item.details)}`}>{priorityLabels[requestPriority(item.details)]}</span></div><p className="operation-help">신청 {dateKey(new Date(item.timestamp))} {timeLabel(item.timestamp)}</p>{item.details?.topics.length ? <div className="request-topics"><strong>고민 주제</strong>{item.details.topics.map(topic => <span key={topic}>{counselingTopics[topic]}</span>)}</div> : <p><strong>고민 주제:</strong> 이전 신청 · 선택 없음</p>}<p><strong>보호자 연락처:</strong> {item.details ? item.details.noContact ? '선생님이 확인해 주세요' : `${item.details.guardianRelation ? `${guardianRelations[item.details.guardianRelation]} · ` : ''}${item.details.contact}` : '이전 신청 · 전화번호 없음'}</p>
      <details><summary>학생 답변 보기</summary>{item.details ? Object.entries(safetyQuestions).map(([key, question]) => <p key={key}>{question}<br /><strong>{item.details!.screening[key as keyof typeof safetyQuestions] === 'yes' ? '네' : item.details!.screening[key as keyof typeof safetyQuestions] === 'no' ? '아니요' : '선생님께 직접 이야기하고 싶음'}</strong></p>) : <p>이전 신청에는 안전 확인 답변이 없습니다.</p>}</details><div className="roster-actions">{item.completed ? <span>학생 확인·상담 안내 마침</span> : <button className="admin-nav" onClick={() => { if (!onSave(readRequests().map(row => row.id === item.id ? { ...row, completed: true } : row))) setError('저장하지 못했습니다.'); else setError('') }}>학생 확인·상담 안내 마침</button>}</div></article>)}</div>{!rows.length && <p className="admin-empty">해당하는 신청이 없습니다.</p>}<p className="storage-note">전화번호와 학생 답변은 이 기기의 브라우저에만 저장됩니다. 실제 학생 정보를 받으려면 먼저 관리자 로그인과 학생 정보를 보호하는 서버를 연결해야 합니다.</p></>
}
